#!/usr/bin/env python3

import sys

from pathlib import Path
from my_io import parse_file, save_solution
from algo import solve


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Incorrect number of args!")
        exit(-1)

    books, libs, days = parse_file(Path(sys.argv[1]))
    solution_libs = solve(books, libs, days)
    save_solution(solution_libs, sys.argv[1])

    print('Books: {}'.format(books))
    print(libs)
    print('Days: {}'.format(days))
