#! /usr/bin/env python3

import sys

from pathlib import Path
from input import parse_file


books = []
libs = []
days = 0

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Incorrect number of args!")
        exit(-1)

    books, libs, days = parse_file(Path(sys.argv[1]))
    print('Books: {}'.format(books))
    print('Days: {}'.format(days))
